### ISSUE TITLE
clean_up function is dropping collection along with any indexes defined for collection

### ISSUE THREAD

**Issue by rcodesmith** [jcteague/mongoose-fixtures#2]
After using the clean_up function in a test, the collections are dropped, including any indexes that were defined for the collection.  This is causing other tests that depend on those indexes being present to fail (e.g. unique constraints).

e.g. in mocha test:

```
    after(function(done){fixtures.clean_up(done)});
```

The clean_up() function is using the Mongoose collection drop() function.  If it used remove() instead, it would remove all documents from the collection, but keep the indexes intact.

**Comment by jcteague** [comment]
Thanks, I merged your pull request.
